main: com.kookykraftmc.CatBot.CatBot
name: CatBot
version: 4.2
authors: [Time6628, Kraise_]
depend: [Vault]
description: KKMC's ChatBox plugin.

commands:
  catbot:
    description: Do stuff with catbot
    usage: /catbot reload|pet|redeem|warn